KPMP-3670-insert-new-database-into-the-docker-compose-for-DL-environment
KPMP/heavens-docker pull request #254
Opened 2022-08-08 18:28 UTC by abarkellumich

2022-08-10 20:48 UTC, rlreamy requested changes

2022-08-11 15:10 UTC, abarkellumich commented on eridanus/docker-compose.dev.yml
> +  local:
Yes, this did work for me and I was able to login and connect (dev-upload). I'll try the dataLake network though

2022-08-15 15:32 UTC, rlreamy requested changes

2022-08-15 15:32 UTC, rlreamy commented on eridanus/docker-compose.dev.yml
> +      local:
Pretty sure you are going to want this on the dataLake network, not the local network.

2022-08-15 18:04 UTC, abarkellumich commented on eridanus/docker-compose.dev.yml
> +  local:
Removed, forgot to update dev as well

2022-08-15 18:50 UTC, rlreamy approved these changes

2022-08-15 18:50 UTC, merged